// <auto-generated />
using System;
using CovAuto.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovAuto.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316100915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CovAuto.API.Domain.Entities.ServiceTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Regio Noord-Holland",
                            Name = "Noord Service",
                            PlannerName = "Linda van Noord"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Regio Zuid-Holland",
                            Name = "Zuid Service",
                            PlannerName = "Ahmed El Farsi"
                        });
                });

            modelBuilder.Entity("CovAuto.API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Linda van Noord",
                            PasswordHash = "$2a$11$CtVfTc19Zo6wqxhu6FaEp.XC83OAZastaj4jl.OVrpVwcYVykck7e",
                            Role = "Planner",
                            Username = "planner.noord"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Ahmed El Farsi",
                            PasswordHash = "$2a$11$CtVfTc19Zo6wqxhu6FaEp.XC83OAZastaj4jl.OVrpVwcYVykck7e",
                            Role = "Planner",
                            Username = "planner.zuid"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Jan de Vries",
                            PasswordHash = "$2a$11$CtVfTc19Zo6wqxhu6FaEp.XC83OAZastaj4jl.OVrpVwcYVykck7e",
                            Role = "Monteur",
                            ServiceTeamId = 1,
                            Username = "monteur.jan"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Fatma Yilmaz",
                            PasswordHash = "$2a$11$CtVfTc19Zo6wqxhu6FaEp.XC83OAZastaj4jl.OVrpVwcYVykck7e",
                            Role = "Monteur",
                            ServiceTeamId = 1,
                            Username = "monteur.fatma"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Sven Bakker",
                            PasswordHash = "$2a$11$CtVfTc19Zo6wqxhu6FaEp.XC83OAZastaj4jl.OVrpVwcYVykck7e",
                            Role = "Monteur",
                            ServiceTeamId = 2,
                            Username = "monteur.sven"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Ayse Demir",
                            PasswordHash = "$2a$11$CtVfTc19Zo6wqxhu6FaEp.XC83OAZastaj4jl.OVrpVwcYVykck7e",
                            Role = "Monteur",
                            ServiceTeamId = 2,
                            Username = "monteur.ayse"
                        });
                });

            modelBuilder.Entity("CovAuto.API.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTeamId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hoofdstraat 12, Amsterdam",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Familie Jansen",
                            Description = "CV-ketel geeft foutcode E5.",
                            EstimatedHours = 3.0,
                            Priority = "Hoog",
                            ScheduledFor = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Nieuw",
                            Title = "Storing CV-ketel repareren"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kalverstraat 88, Amsterdam",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Dhr. Peters",
                            Description = "Verouderde groepenkast vervangen.",
                            EstimatedHours = 6.0,
                            Priority = "Normaal",
                            ScheduledFor = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Gepland",
                            Title = "Vervangen groepenkast"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Industrieweg 5, Haarlem",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Kantoor Bakker B.V.",
                            Description = "Jaarlijks onderhoud WTW-installatie.",
                            EstimatedHours = 4.5,
                            Priority = "Normaal",
                            ScheduledFor = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "InUitvoering",
                            Title = "Onderhoud ventilatiesysteem"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Zonnebloemstraat 7, Alkmaar",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fam. de Groot",
                            Description = "Jaarlijkse inspectie en schoonmaak.",
                            EstimatedHours = 2.0,
                            Priority = "Laag",
                            ScheduledFor = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Voltooid",
                            Title = "Inspectie zonnepanelen"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rozenstraat 3, Zaandam",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Mevr. Smit",
                            Description = "Lekkage onder de keuken.",
                            EstimatedHours = 2.5,
                            Priority = "Hoog",
                            ScheduledFor = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Nieuw",
                            Title = "Lekkage waterleidingen verhelpen"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Merenweg 21, Purmerend",
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fam. Visser",
                            Description = "Nieuwe warmtepomp plaatsen en aansluiten.",
                            EstimatedHours = 8.0,
                            Priority = "Normaal",
                            ScheduledFor = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Gepland",
                            Title = "Installatie warmtepomp"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Tulpstraat 15, Amsterdam",
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Dhr. Nguyen",
                            Description = "Geen stroom op verdieping.",
                            EstimatedHours = 3.5,
                            Priority = "Kritiek",
                            ScheduledFor = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Nieuw",
                            Title = "Storing elektra woning"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Rozenhof 1-20, Haarlem",
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "VVE Rozenhof",
                            Description = "Alle radiatorkranen vervangen.",
                            EstimatedHours = 5.0,
                            Priority = "Normaal",
                            ScheduledFor = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 1,
                            Status = "Gepland",
                            Title = "Vervangen radiatorkranen"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Hotelplein 1, Rotterdam",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Hotel Rotterdam",
                            Description = "Filters reinigen en koelmiddel controleren.",
                            EstimatedHours = 3.0,
                            Priority = "Normaal",
                            ScheduledFor = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "Gepland",
                            Title = "Onderhoud airconditioning"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Bergweg 42, Rotterdam",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fam. Hassan",
                            Description = "Dakgoot verstopt en lekkend.",
                            EstimatedHours = 2.0,
                            Priority = "Hoog",
                            ScheduledFor = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "Voltooid",
                            Title = "Reparatie dakgoot"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Parkweg 9, Dordrecht",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Dhr. van Dijk",
                            Description = "Laadpaal installeren in garage.",
                            EstimatedHours = 4.0,
                            Priority = "Normaal",
                            ScheduledFor = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "Nieuw",
                            Title = "Plaatsen laadpaal elektrisch voertuig"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Haagweg 100, Den Haag",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Woningcorp De Haag",
                            Description = "Storing in centrale verwarmingsinstallatie.",
                            EstimatedHours = 6.0,
                            Priority = "Kritiek",
                            ScheduledFor = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "InUitvoering",
                            Title = "Storing cv-ketel flatgebouw"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Winkelcentrum Zuid, Delft",
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Supermarkt Koops",
                            Description = "Jaarlijkse veiligheidscontrole.",
                            EstimatedHours = 1.5,
                            Priority = "Hoog",
                            ScheduledFor = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "Voltooid",
                            Title = "Inspectie gasleiding"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kelderlaan 5, Zoetermeer",
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fam. de Bruijn",
                            Description = "Gebarsten waterleiding in kelder.",
                            EstimatedHours = 3.5,
                            Priority = "Hoog",
                            ScheduledFor = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "Gepland",
                            Title = "Reparatie waterpijp"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Vermeerstraat 18, Leiden",
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fam. Vermeer",
                            Description = "Smart home systeem installeren.",
                            EstimatedHours = 7.0,
                            Priority = "Laag",
                            ScheduledFor = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTeamId = 2,
                            Status = "Nieuw",
                            Title = "Installatie domotica systeem"
                        });
                });

            modelBuilder.Entity("CovAuto.API.Domain.Entities.User", b =>
                {
                    b.HasOne("CovAuto.API.Domain.Entities.ServiceTeam", "ServiceTeam")
                        .WithMany("Members")
                        .HasForeignKey("ServiceTeamId");

                    b.Navigation("ServiceTeam");
                });

            modelBuilder.Entity("CovAuto.API.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("CovAuto.API.Domain.Entities.ServiceTeam", "ServiceTeam")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ServiceTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceTeam");
                });

            modelBuilder.Entity("CovAuto.API.Domain.Entities.ServiceTeam", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}